name: Update CSV

on:
  push:
    branches:
      - main

jobs:
  update-csv:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Update CSV
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add phrases.csv
          if git diff-index --quiet HEAD --; then
            echo "No changes to commit"
          else
            git commit -m 'Update phrases.csv'
            git push
          fi
